version: "3"

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: newdb
    ports:
      - "5433:5432"  # Changed to avoid conflicts with local postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: nodeapp
    ports: 
      - 8000:8000
    depends_on:
      database:
        condition: service_healthy